### PR TITLE
fix: PostgreSQL supports newline in quoted literals and identifiers

### LINKED ISSUE #1730: PostgreSQL statement parsing fails on string literals with newline characters
The PostgreSQL statement parser that removes comments and determines how many query parameters are in a query fails if the statement contains one or more string literals or quoted identifiers that contain a newline character.

So the following statements fail with an `INVALID_ARGUMENT: SQL statement contains an unclosed literal` error:

```sql
select 'test1
test2';

select "foo
bar" from some_table;
```

### PR DESCRIPTION
**Pull request by olavloite**
PostgreSQL supports newline characters in string literals and quoted
identifiers. Trying to execute a statement with a string literal or
quoted identifier that contained a newline character would cause an
'Unclosed string literal' error.

Fixes #1730

### CODE REVIEW

File: google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/PostgreSQLStatementParser.java [hunk 1]
```diff
@@ -56,95 +56,44 @@ protected boolean supportsExplain() {
   @Override
   String removeCommentsAndTrimInternal(String sql) {
     Preconditions.checkNotNull(sql);
-    String currentTag = null;
```
Comment (olavloite) [inline google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/PostgreSQLStatementParser.java:59]: It might be easier to open the entire file (online or in an IDE) to review it, than to try to do that based on this diff render from GitHub. The parser code has also been compacted a lot, as there was quite a lot of code duplication, and that makes this diff render a lot harder to read.

File: google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/PostgreSQLStatementParser.java [hunk 2]
```diff
@@ -56,95 +56,44 @@ protected boolean supportsExplain() {
...
-            multiLineCommentLevel++;
-            index++;
-          }
+        // Check for -- which indicates the start of a single-line comment.
+        if (sql.length() > index + 1 && c == HYPHEN && sql.charAt(index + 1) == HYPHEN) {
+          // This is a single line comment.
+          isInSingleLineComment = true;
+          index += 2;
+          continue;
+        } else if (sql.length() > index + 1 && c == SLASH && sql.charAt(index + 1) == ASTERIKS) {
```
Comment (thiagotnunes) [inline google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/PostgreSQLStatementParser.java:86]: typo `ASTERIKS -> ASTERISKS`?

**Review by thiagotnunes — APPROVED** [review]

File: google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/PostgreSQLStatementParser.java (hunk 2 above)
Comment (olavloite) [reply google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/PostgreSQLStatementParser.java]: Fixed
