### PR TITLE
fix: retries of updates in the Connection API ignored analyze mode

### LINKED ISSUE #2009: analyzeUpdate is executed as executeUpdate during retry in the Connection API
If `analyzeUpdate(Statement)` is executed in a read/write transaction in the Connection API, and the read/write transaction is aborted, the retry will retry the statement as `executeUpdate(Statement)` instead of `analyzeUpdate(Statement)`. This will fail, either because the update count that is returned is different, or because the statement contained parameters and these were not bound for the analyze.

### PR DESCRIPTION
**Pull request by olavloite**
Retries of read/write transactions in the Connection API did not respect the analyze mode of update statements. This would cause updates to be executed using AnalyzeMode.NORMAL during retries, regardless of what was used during the initial attempt.

Fixes #2009

### CODE REVIEW

File: google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/RetriableUpdate.java [hunk 1]
```diff
@@ -54,7 +57,15 @@ public void retry(AbortedException aborted) throws AbortedException {
       transaction
           .getStatementExecutor()
           .invokeInterceptors(statement, StatementExecutionStep.RETRY_STATEMENT, transaction);
-      newCount = transaction.getReadContext().executeUpdate(statement.getStatement(), options);
+      if (analyzeMode == null || analyzeMode == AnalyzeMode.NONE) {
```
Comment (rajatbhatta) [inline google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/RetriableUpdate.java:60]: I think we can check only for `AnalyzeMode.NONE` here, as we never pass in `analyzeMode` as `null`. We could also do a `Preconditions.checkNotNull(analyzeMode)` in the constructor.
```suggestion
      if (analyzeMode == AnalyzeMode.NONE) {
```

We should either do the above or add the `null` handling to below as well (as in the current state of code, it would not call `executeUpdate` for `null` analyzeMode case): https://github.com/googleapis/java-spanner/blob/1974f924eb2c4c9aea2638100d71fa1cace9dc17/google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ReadWriteTransaction.java#L431.

**Review by rajatbhatta — APPROVED** [review]
LGTM.
