### PR TITLE
test: increase timeout to prevent flakiness

### LINKED ISSUE #1969: DatabaseClientImplTest is flaky in windows build
```
Error:  Failures: 
Error:    DatabaseClientImplTest.testPartitionedDmlDoesNotTimeout:1080 expected com.google.cloud.spanner.SpannerException to be thrown, but nothing was thrown
```

From https://github.com/googleapis/java-spanner/pull/1958

### PR DESCRIPTION
**Pull request by rajatbhatta**
Increase test timeout to prevent flaky failures on slow build environments.

Fixes #1969

### CODE REVIEW

File: google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java [hunk 1]
```diff
@@ -1053,10 +1053,10 @@ public void testPartitionedDmlDoesNotTimeout() {
     mockSpanner.setExecuteSqlExecutionTime(SimulatedExecutionTime.ofMinimumAndRandomTime(10, 0));
```
Comment (olavloite) [inline google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java:1053]: I think you need to increase this value instead of the values below. This is the time that the server will wait to simulate that the DML statement takes a 'long' time. The values below are the times that the client should wait before throwing a deadline exceeded error.

Comment (rajatbhatta) [reply google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java]: Thanks for clarifying.

**Review by olavloite — APPROVED** [review]

**Review by ansh0l — APPROVED** [review]

**Comment by suztomo** [comment]
Thank you!
