### PR TITLE
test: only use one backup for integration test

### LINKED ISSUE #1436: spanner.it.slow.ITBackupTest: testBackups failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: ac835ca227dc11b7530140314ad27c56d69091b8
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/1aa17970-ab0b-4d71-b4f3-7dcdabd9ac39), [Sponge](http://sponge2/1aa17970-ab0b-4d71-b4f3-7dcdabd9ac39)
status: failed
<details><summary>Test output</summary><br><pre>com.google.cloud.spanner.SpannerException: DEADLINE_EXCEEDED: Backup1 still not finished. Test is giving up waiting for it.
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:284)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:61)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:56)
	at com.google.cloud.spanner.it.slow.ITBackupTest.testBackups(ITBackupTest.java:299)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
</pre></details>

### PR DESCRIPTION
**Pull request by olavloite**
Changes the integration test for backups to only create one backup to reduce the probability of a build timeout, and increases the build timeout for the `SlowTest` execution to 7,200 seconds.

Fixes #1436

### CODE REVIEW

File: google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/slow/ITBackupTest.java [hunk 1]
```diff
@@ -175,31 +174,40 @@ public void setUp() {
...
 
-  private void waitForDbOperations(String backupId) throws InterruptedException {
+  private static void waitForDbOperations(String backupId) throws InterruptedException {
     try {
       Backup backupMetadata =
           dbAdminClient.getBackup(testHelper.getInstanceId().getInstance(), backupId);
       boolean allDbOpsDone = false;
       while (!allDbOpsDone) {
         allDbOpsDone = true;
+        assertNotNull(backupMetadata.getProto());
```
Comment (thiagotnunes) [inline google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/slow/ITBackupTest.java:200]: Should this be pushed outside of the `while` loop, since we only update the `backupMetadata` in the beginning of the `try` block?

File: google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/slow/ITBackupTest.java [hunk 2]
```diff
@@ -223,121 +231,74 @@ private void waitForDbOperations(String backupId) throws InterruptedException {
...
+    final Database sourceDatabase =
         dbAdminClient
-            .newDatabaseBuilder(DatabaseId.of(projectId, instanceId, db1Id))
+            .newDatabaseBuilder(DatabaseId.of(projectId, instanceId, databaseId))
             .setEncryptionConfig(EncryptionConfigs.customerManagedEncryption(keyName))
             .build();
-    logger.info(String.format("Creating test database %s", db1Id));
-    OperationFuture<Database, CreateDatabaseMetadata> dbOp1 =
+    logger.info(String.format("Creating test database %s", databaseId));
+    OperationFuture<Database, CreateDatabaseMetadata> dbOp =
```
Comment (thiagotnunes) [inline google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/slow/ITBackupTest.java:242]: nit: `dbOp -> databaseOperation`

File: google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/slow/ITBackupTest.java [hunk 3]
```diff
@@ -347,60 +308,58 @@ public void testBackups() throws InterruptedException, ExecutionException, Timeo
     // Test listing operations.
     // List all backups.
     logger.info("Listing all backups");
-    assertThat(instance.listBackups().iterateAll()).containsAtLeast(backup1, backup2);
+    assertThat(instance.listBackups().iterateAll()).contains(backup);
```
Comment (thiagotnunes) [inline google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/slow/ITBackupTest.java:311]: nit: replace `assertThat` by `assertEquals`, `assertTrue`, ...

**Review by thiagotnunes — APPROVED** [review]

File: google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/slow/ITBackupTest.java (hunk 3 above)
Comment (olavloite) [reply google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/slow/ITBackupTest.java]: Done, here and elsewhere in this file
