### PR TITLE
test: Creating dummy spanner instance for ITInstanceAdminTest

### LINKED ISSUE #1626: ITInstanceAdminTest #update / #updateViaEntity fail when two tests are running simultaneously
The update and updateViaEntity tests update the current instance display name to a random one. If there are two tests running simultaneously the assertions might fail, because the updated name can match the wrong display name.

We need to fix these tests so that they are self-contained.

### PR DESCRIPTION
**Pull request by gauravpurohit06**
Fixes #1626

### CODE REVIEW

File: google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestEnv.java [hunk 1]
```diff
@@ -58,8 +58,15 @@ public class IntegrationTestEnv extends ExternalResource {
...
   private DatabaseAdminClient databaseAdminClient;
   private boolean isOwnedInstance;
+  private boolean useNewInstance;
   private RemoteSpannerHelper testHelper;
 
+  public IntegrationTestEnv(final boolean useNewInstance) {
+    this.useNewInstance = useNewInstance;
+  }
+
+  public IntegrationTestEnv() {}
```
Comment (rajatbhatta) [inline google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestEnv.java:68]: Should we set a default value for useNewInstance in this constructor?
```suggestion
  public IntegrationTestEnv() {
    this.useNewInstance = false;
  }
```

**Review by rajatbhatta — CHANGES_REQUESTED** [review]
Overall it looks good to me, except a comment. PTAL.

File: google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestEnv.java (hunk 1 above)
Comment (olavloite) [reply google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestEnv.java:68]: A couple of nits regarding this:
1. It is common to have constructors with less parameters before constructors with more parameters (i.e. move this one to line 63)
2. It is good practice to reuse code in constructors, so I would suggest calling `this(false)` from the parameter-less constructor.

File: google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestEnv.java [hunk 2]
```diff
@@ -58,8 +58,15 @@ public class IntegrationTestEnv extends ExternalResource {
   private InstanceAdminClient instanceAdminClient;
   private DatabaseAdminClient databaseAdminClient;
   private boolean isOwnedInstance;
+  private boolean useNewInstance;
```
Comment (olavloite) [inline google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestEnv.java:61]: nit: Maybe rename to `alwaysUseOwnedInstance`?

File: google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITInstanceAdminTest.java [hunk 3]
```diff
@@ -45,11 +45,12 @@
 @Category(SerialIntegrationTest.class)
```
Comment (olavloite) [inline google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITInstanceAdminTest.java:45]: As this is now always using an owned instance, you can probably change this to a `ParallelIntegrationTest`.

File: google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestEnv.java (hunk 2 above)
Comment (gauravpurohit06) [reply google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestEnv.java:61]: Thanks Knut. It seems like a bit confusing with `isOwnedInstance`, can we use `createNewInstance`?

Comment (olavloite) [reply google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestEnv.java]: Could we in that case use `alwaysCreateNewInstance`. My point is that any of these tests __could__ create a new instance. I think it will be confusing if the test creates a new instance while the property `createNewInstance` is `false`. The `always` prefix indicates that it forces the specific test to always create a new instance, regardless whether the test environment has defined an existing instance name that should be used.

**Review by olavloite — APPROVED** [review]
LGTM, with a suggestion regarding the naming of the `createNewInstance` / `alwaysCreateNewInstance` property.

**Review by rajatbhatta — APPROVED** [review]
LGTM.
