### PR TITLE
Fix: multiple calls to end of span

### LINKED ISSUE #71: spanner: "OVERKILLED java.lang.IllegalStateException: refCount dropped below zero" warning
I have seen a few reports of warning messages polluting error logs.

#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
Spanner
2. OS type and version: Linux but version unknown
3. Java version: Unknown
4. spanner version(s): 1.43.0

#### Steps to reproduce

I haven't reproduced this yet but I suspect this happens when an error occurs during [`ResumableStreamIterator.computeNext().`](https://github.com/googleapis/java-spanner/blob/1178958eaec5aa6ea80938ad91dfb0b1a688463d/google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java#L929) The trace span is ended with [`TraceUtil.endSpanWithFailure(span, e)`](https://github.com/googleapis/java-spanner/blob/1178958eaec5aa6ea80938ad91dfb0b1a688463d/google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java#L1000) but then when the stream iterator is closed, the code attempts to [end the span](https://github.com/googleapis/java-spanner/blob/1178958eaec5aa6ea80938ad91dfb0b1a688463d/google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java#L924) again.

#### Stack trace
```
WARNING: <span:26a180bf406e2db9, parent:4479af252f884e07, trace:842cc1d5df736326, mask:ffffffff98000080, name:CloudSpannerOperation.ExecuteStreamingQuery>: OVERKILLED
java.lang.IllegalStateException: refCount dropped below zero
	at com.google.tracing.TraceContext.unRef(TraceContext.java:799)
	at com.google.perftools.opencensus.trace.SpanImpl.end(SpanImpl.java:237)
	at io.opencensus.trace.Span.end(Span.java:244)
	at com.google.cloud.spanner.AbstractResultSet$ResumableStreamIterator.close(AbstractResultSet.java:850)
	at com.google.cloud.spanner.AbstractResultSet$GrpcValueIterator.close(AbstractResultSet.java:285)
	at com.google.cloud.spanner.AbstractResultSet$GrpcResultSet.close(AbstractResultSet.java:133)
	at com.google.cloud.spanner.AbstractResultSet$GrpcResultSet.yieldError(AbstractResultSet.java:144)
	at com.google.cloud.spanner.AbstractResultSet$GrpcResultSet.next(AbstractResultSet.java:121)
	at com.google.cloud.spanner.ForwardingResultSet.next(ForwardingResultSet.java:47)
	at com.google.cloud.spanner.SessionPool$AutoClosingReadContext$1.internalNext(SessionPool.java:151)
	at com.google.cloud.spanner.SessionPool$AutoClosingReadContext$1.next(SessionPool.java:141)
```

### PR DESCRIPTION
**Pull request by mayurkale22**
Fixes #71

### CODE REVIEW

File: google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java [hunk 1]
```diff
@@ -892,7 +892,7 @@ private PooledSession take() throws SpannerException {
             return s.session;
           }
         } catch (Exception e) {
-          TraceUtil.endSpanWithFailure(tracer.getCurrentSpan(), e);
```
Comment (mayurkale22) [inline google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java]: `tracer.getCurrentSpan()` is called outside of scope, which means `endSpanWithFailure` will execute on either READ_WRITE_TRANSACTION or READ_ONLY_TRANSACTION span instead of WAIT_FOR_SESSION span.

**Comment by mayurkale22** [comment]
@rghetia Could you please review PR?

File: google-cloud-spanner/src/main/java/com/google/cloud/spanner/TraceUtil.java [hunk 2]
```diff
@@ -54,6 +54,16 @@
...
+    if (e instanceof SpannerException) {
+      span.setStatus(
+          StatusConverter.fromGrpcStatus(((SpannerException) e).getErrorCode().getGrpcStatus())
+              .withDescription(e.getMessage()));
+    } else {
+      span.setStatus(Status.INTERNAL.withDescription(e.getMessage()));
+    }
+  }
+
   static void endSpanWithFailure(Span span, Throwable e) {
```
Comment (rghetia) [inline google-cloud-spanner/src/main/java/com/google/cloud/spanner/TraceUtil.java]: is endSpanWithFailure used anywhere now? If not then please remove it.

Comment (mayurkale22) [reply google-cloud-spanner/src/main/java/com/google/cloud/spanner/TraceUtil.java]: This has been used in a few places (ex: [singleUse](https://github.com/googleapis/java-spanner/blob/master/google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClientImpl.java#L113)) where span does not end except when there is a failure.

See: https://github.com/googleapis/google-cloud-java/pull/2677/files#r157323309 for original reason.

**Comment by mayurkale22** [comment]
@olavloite could you please help me to fix the tests? Here is the issue: When I ran `SpanTest` and `SpannerGaxRetryTest` separately, they work as expected but saw tests failures when running together (`mvn test`). I suspect it is due to reflection that we used to set the test tracer in `SpanTest`. I am trying to solve it locally, no luck so far.

**Comment by olavloite** [comment]
> @olavloite could you please help me to fix the tests? Here is the issue: When I ran `SpanTest` and `SpannerGaxRetryTest` separately, they work as expected but saw tests failures when running together (`mvn test`). I suspect it is due to reflection that we used to set the test tracer in `SpanTest`. I am trying to solve it locally, no luck so far.

@mayurkale22 
https://github.com/mayurkale22/java-spanner/pull/2 should do the trick.

**Comment by mayurkale22** [comment]
> [mayurkale22#2](https://github.com/mayurkale22/java-spanner/pull/2) should do the trick.

Thanks for the help.

> the reason that other test cases are failing could be an indication that there are still conditions possible that could trigger a span to be ended multiple times. It would therefore be interesting to investigate those specific failures and see if you can reproduce them in the SpanTest class.

I managed to repro-d the issue in `SpannerGaxRetryTest`, will try to fix it soon.

**Comment by mayurkale22** [comment]
@olavloite I have added a few more tests and attempted to fix remaining issues, PTAL c0689bd4ecce3dcb6b2397b6dc802b3339372c83 when you get a chance.

**Comment by mayurkale22** [comment]
> LGTM.
> I don't quite get where the dependency problem is coming from. It can be fixed by adding the following to the `<ignoredDependencies>` tag in the `pom.xml`: `com.google.errorprone:error_prone_annotations`

Great. Finally, build is passed.

**Comment by mayurkale22** [comment]
@rghetia would like to get your eyes on OpenCensus related changes. Please review when you get a chance.

**Comment by mayurkale22** [comment]
@skuruppu I think this is good to merge now.
